FROM signoz/signoz-schema-migrator:v0.111.42

# --cluster-name "" disables ON CLUSTER DDL (requires ZooKeeper)
CMD ["sync", "--dsn", "tcp://default:signoz123@clickhouse.railway.internal:9000", "--cluster-name", ""]
